### ISSUE TITLE
SRA TF ChIP-seq curate sample list

### ISSUE THREAD

**Issue by jfear** [jfear/s2rnai#107]
### Story
In #70 I created a list of TF ChIP-seq datasets. We want to curate this list by hand and determine which datasets are really TF ChIP-seq.

### Questions and Tasks
- [ ] What samples appear to be ChIP-seq?
- [ ] What samples appear to be TF ChIP-seq?

### Definition of done
- [ ] A golden list of TF ChIP-seq SRX identifiers.
