### ISSUE TITLE
Upstream conservation clustering

### ISSUE THREAD

**Issue by jfear** [jfear/s2rnai#111]
### Story
There is an interesting pattern of conservation/GC content just upstream of the TSS. We want to determiner if there are different classes of promoters. To look at this we will use different approaches to classify transcripts/genes. We can then look for biological signal to determine why these classes exist.

### Questions and Tasks
- [x] Have others already looked of patterns of conservation upstream of TSS? [lit review]
- [ ] What conservation patterns upstream of D. melanogaster TSS?
- [ ] How many classes of promoters can we identify?
- [ ] Do orthologous genes have a similar conservation upstream?

### Definition of done
- [ ] Have a table classifying transcripts/genes into different clusters based on upstream conservation score.
- [ ] Have a summary report looking for biological meaning in clustered groups.
