### ISSUE TITLE
s2RNAi Dataprep and QC

### ISSUE THREAD

**Issue by jfear** [jfear/s2rnai#22]
### Story

Lee has a large S2R+ RNAi screen where he knocked out ~587 TF and measured the expression profile. For each TF he used 2 different RNAi reagents, which in his preliminary analysis some showed different effects. We need to re-analyze this data and determine:

1. Get the data into good shape with a solid and defined analysis
2. Decide if this data will work as a validation study.

### Questions and Tasks
- [x] Create sample table using GEO entry.
- [x] Set up RNA-seq workflow.
- [x] Run RNA-seq workflow.
- [ ] Tweak workflow if needed.
- [ ] Are all samples high quality.

### Definition of done
- [ ] Have a completed RNA-seq workflow.
- [ ] Go through QC and determine overall sample quality.
