### ISSUE TITLE
modENCODE TF ChIP-seq

### ISSUE THREAD

**Issue by jfear** [jfear/s2rnai#61]
### Story
Yijie needs a weight matrix for ChIP and Histone data. modENCODE has the largest source of this type of data for D. mel. We need to identify all of the datasets and use them to build several weight matrices. Ideally we will generate a conservative matrix and a more relaxed matrix.

### Questions and Tasks
- [ ] What are the modENCODE guidelines for ChIP-Seq?
    - Discussed [here](https://paperpile.com/shared/yBnKtv)
    - The focus on antibody characterization. If any results seem strange may want to go back to the paper and verify that this was done. 
    - They claim that only 2 replicates are necessary (which I disagree with), and suggest using IDR to compare between replicates.
    - Suggest 20 million reads for point-source.
    - Suggest using both "input" and "IgG" controls.
    - Try multiple peak callers
    - Evaluate (browser track, FRiP ≥1%,strand cross corr ≥1, IDR ) 

### Definition of done
Deliver two weight matrices g x tf that has a binary indicator of if a TF had a peak in the gene.  
- [ ] Conservative matrix (stringent criteria and phantom peak subtracted)
- [ ] Liberal matrix (more lenient criteria for filtering peaks)
