### ISSUE TITLE
FARE-seq

### ISSUE THREAD

**Issue by jfear** [jfear/s2rnai#66]
### Story
FARE-seq is one method to determine DNA accessibility. Brian related it to looking at ChIP-seq inputs for signal. If this is indeed true, then we need to compile a list of FARE-seq samples and ChIP-seq inputs for S2 cells.

### Questions and Tasks
- [ ] What exactly is FARE-seq?
- [ ] Are ChIP-seq inputs a stand in for FARE-seq?
- [ ] Can we use FARE-seq/ChIP-seq inputs to measure DNA accessibility?
- [ ] Compile list of FARE-seq/ChIP-seq inputs for S2 cell?
- [ ] Compile list of FARE-seq/ChIP-seq inputs for other D. mel data?

### Definition of done
if FARE-seq/ChIP-seq inputs will work:
    - [ ] Compiled list of FARE-seq
    - [ ] Weight matrix showing DNA accessibility. 
else:
    - Mark as Done
