### ISSUE TITLE
Generate list of possible motifs.

### ISSUE THREAD

**Issue by jfear** [jfear/s2rnai#74]
### Story
We have decided to refine the region which we look for motif binding sites. Previously we were looking throughout the entire genome or within the gene body and 1 kb upstream. We have decided to focus only within introns and 1 kb upstream of the gene start. 

### Tasks
- [x] Decide how to slice and dice.
- [x] Create a BED file with introns and 1 kb upstream regions.
- [x] Create BED file with all possible motifs.

### Questions
- [x] How many motif sites are there per TF?
Out of the 339 TFs in the dataset, the average number of motif sites is about 31,000 (no filtering)
count	339.000000
**mean	31130.200590**
std	26223.012666
min	2623.000000
25%	15960.000000
50%	24541.000000
75%	39175.500000
max	302140.000000

### Definition of done
- [ ] BED file for each TF with motifs form intron and 1 kb upstream.
