### ISSUE TITLE
Conservative motif matrix

### ISSUE THREAD

**Issue by jfear** [jfear/s2rnai#75]
### Story
We need to create a motif (TF->gene) weight matrix. We have motifs from a set of TFs, but want to create a conservative list of motif sites. We will filter motifs from #74 and create this "gold" set. Filtering we will use a combination of p-value/q-value and phastcons scores. We may need to revisit when we have chromatin status.

### Tasks
- [ ] Adjust FDR if needed.
- [ ] Develop score metric
- [ ] Identify cutoff critera
- [ ] construct golden set of motifs
- [ ] Build weight matrix

### Questions
- [ ] How can we combine p-value/q-value with phastcons?
- [ ] Are p-value related with phastcons? [plot -log(p-value) vs phastcons]
- [ ] What is the distribution of our metric?
- [ ] Can we use a 95% cutoff or do we need to do something more rigorous?
- [ ] Should we use a Bon Ferroni adjustment instead of FDR?

### Definition of done
- [ ] Have a defined metric and cutoff criteria
- [ ] A motif weight matrix for as many TFs as possible.
