### ISSUE TITLE
How can we use phastcons scores?

### ISSUE THREAD

**Issue by jfear** [jfear/s2rnai#76]
### Story
Conservation scores are important for identify genomic regions of interest. There may be some ideas that we can gain just by thinking about conservation scores.

### Questions and Tasks
- [ ] How can we use low conservation to our advantage?
    * There is a drop in conservation immediately upstream of promoter. perhaps regions of ultra low conservation are as important as regions of high conservation.
- [x] How does GC content play a role in the phastcons score drop near TSS?
Both GC content and phastcons scores follow a similar pattern around the TSS 
    * [x] Plot heatmap centered at TSS with GC content.
- [ ] Are there classes of genes with different patterns of conservation surrounding TSS?
    * Take the sum/median/mean of conservation score and cluster genes
    * Get list of genes form Haiwang that may behave differently. 

### Definition of done
This is an open ended story. It requires some discussion with the group. We can consider this done if we are happy with how we are using phastcons scores for generating the motif weight matrix and maybe ChIP-seq matrices.
