### ISSUE TITLE
s2RNAi Initial DE

### ISSUE THREAD

**Issue by jfear** [jfear/s2rnai#79]
### Story
Need to perform a complete differential expression analysis.

### Questions and Tasks
- [ ] Remove dsRNA regions before analysis.
- [ ] Are reagents positively correlated?
- [ ] What genes are differentially expressed?
- [ ] Are there reagents with off-target effects?
- [ ] What block effects are there?
- [ ] Can we correct for these block effects?

### Definition of done
- [ ] Fully summarized Differential Expression Analysis
