### ISSUE TITLE
DNASE-Seq

### ISSUE THREAD

**Issue by jfear** [jfear/s2rnai#85]
### Story
Need to see if there are any DNASE-seq or ATAC-seq datasets available in the SRA for S2 cells. It may be possible to use these hypersensitive sites to predict TF occupancy, in order to fill in that we don't have ChIP-seq instead of using raw motifs.

### Questions and Tasks
- [ ] Are there any DNASE-seq or ATAC-seq datasets in SRA?
- [ ] Can we use an algorithm to identify putative binding sites?
    - [ ] Look at https://paperpile.com/shared/HgPrHf
        - [ ] Look at https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3044858/
    - [ ] http://www.nature.com/nbt/journal/v32/n2/full/nbt.2824.html?message-global=remove

### Definition of done
if DNASE-seq or ATAC-seq data exists for S2 cells:
    - [ ] A summary for each TF on the probability of occupancy.
else:
    DONE
