### ISSUE TITLE
Fly Meeting Abstract

### ISSUE THREAD

**Issue by jfear** [jfear/s2rnai#98]
### Story
Isabelle needs an abstract for the Fly Meeting.

### Questions and Tasks
- [ ] What portion of the project should we focus on?
- [ ] What 4 Figures to present?

### Definition of done
- [ ] An abstract submitted to the Fly meeting website.
